apiVersion: apps/v1
kind: Deployment
metadata:
  name: match-service
  labels:
    app: match-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: match-service
  template:
    metadata:
      labels:
        app: match-service
    spec:
      serviceAccountName: match-service-sa 
      imagePullSecrets:
        - name: dockerhub-secret 
      containers:
        - name: match-service
          image: bihou/chess-match-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: PLAYER_SERVICE_URL
              value: "http://player-service/api/players"
            - name: DB_HOST
              value: "postgres"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10